let dialog =  [
    ['Anciano', 'Buenos días caballero. Bienvenido a las tierras de "Javascript".'],
    ['Guerrero', 'Buenos días señor. ¿Quién era ese maldito? ¿Y por qué me atacó?'],
    // ['Anciano', 'Todo el mundo sabe que Alva Majo es desarrollador de videojuegos.'],
    ['Anciano', 'Cuando has dicho que eras Alva era lógico que intente matarte.'],
    ['Anciano', 'Alva Majo odia "Javascript" y todo lo que se hace en estas tierras.'],
    // ['Anciano', 'Esta prohibido hacer videojuegos en "Javascript".'],
    ['Anciano', 'Las tierras de "Javascript" ya no son lo que eran.'],
    ['Guerrero', 'Pues, parece ser un lugar hermozo. Los lagos y las montanias están preciosas.'],
    ['Anciano', 'Así es. Pero últimamente no podemos disfrutar ni de los paisajes ni las bondades de "Javascript".'],
    // ['Anciano', 'Lamentablemente estamos padeciendo tormentos.'],
    ['Anciano', 'La tiranía del Rey Unity y su esposa Unreal han devastado nuestras aldeas.'],
    ['Anciano', 'Ya no permiten realizar VideoJuegos en "Javascript".'],
    ['Anciano', 'Y todo es por culpa de Alva Majo y su influencia. ¡Maldito Influencer!.'],
    ['Guerrero', 'Oh! Lamento mucho oir eso señor.'],
    ['Guerrero', '¿Por qué se les prohibió hacer videojuegos?'],
    ['Anciano', 'Dicen que somos de una raza inferior y que no somos como ellos.'],
    ['Guerrero', 'Todo el mundo sabe que se pueden hacer muy buenos Videojuegos en "Javascript".'],
    ['Guerrero', 'Si el Rey Unity ha prohibido realizar Videojuegos en "Javascript" lo declaro mi enemigo desde hoy mismo.'],
    ['Guerrero', 'Yo soy un guerrero y mi naturaleza es pelear. Daré muerte a ese rey de las sombras.'],
    ['Guerrero', '¿Sabes si alguien se ha revelado contra el Rey Unity?'],
    ['Anciano', 'Muchos lo han intentado, pero mueren al ingresar al castillo protegido por el dragón.'],
    ['Anciano', 'Nadie puede vencer al Rey Unity.'],
    ['Guerrero', 'Yo lo haré. Lo juro por mis dioses y mi amada Dulcinea Konypyon.'],
    ['Anciano', 'Esa no es tarea fácil muchacho. Además del dragón, hay muchos guardias en el castillo.'],
    ['Guerrero', 'Me infiltraré en el castillo, daré muerte al Rey Unity y comeremos dragón con papas esta noche.'],
    ['Guerrero', '¡Lo juro! ¡Como que me llamo Albarracín de Mallorca! Pero me dicen Alva Majo.'],
    // ['Guerrero', 'Desarrollador de Videojuegos indie.'],
    ['Guerrero', 'Dime donde está el castillo. Te lo ordeno.'],
    ['Anciano', 'Vaya nombre te han dado tus padres Albarracín. El mismo nombre del traidor de estas tierras.'],
    ['Anciano', 'Evita mencionar su nombre, de lo contrario aquí en "Javascript" te aniquilarán.'],
    ['Anciano', 'El castillo está a un kilómetro en dirección al sur.'],
    ['Anciano', 'Avisaré a los mercaderes del pueblo que tu irás. Tal vez puedan ayudarte a ingresar al castillo.'],
]

export default dialog