let dialog =  [
    ['Anciano', 'Buenos días caballero. Bienvenido a las tierras de "Javascript".'],
    ['Guerrero', 'Buenos días señor. Gracias. El paisaje de "Javascript" es hermoso. Los lagos y las montanias están preciosas.'],
    ['Anciano', 'Así es. Pero ultimamente no podemos disfrutar ni de los paisajes ni las bondades de "Javascript".'],
    ['Anciano', 'Lamentablemente estamos padeciendo tormentos.'],
    ['Anciano', 'La tiranía del Rey Unity y su esposa Unreal han devastado nuestras aldeas.'],
    ['Anciano', 'Ya no permiten realizar VideoJuegos en "Javascript".'],
    ['Guerrero', 'Oh! Lamento mucho oir eso señor.'],
    ['Guerrero', 'Todo el mundo sabe que se pueden hacer muy buenos Videojuegos en "Javascript".'],
    ['Guerrero', 'Si el Rey Unity ha prohibido realizar Videojuegos en "Javascript" lo declaro mi enemigo desde hoy mismo.'],
    ['Guerrero', 'Yo soy un guerrero y mi naturaleza es pelear.'],
    ['Guerrero', 'Si alguien prohibe hacer juegos en "Javascript" no lo toleraré y daré muerte a quien la merezca.'],
    ['Guerrero', '¿Sabes si alguien se ha revelado contra el Rey Unity?'],
    ['Anciano', 'Muchos lo han intentado, pero mueren al ingresar al castillo protegido por el dragón.'],
    ['Anciano', 'Necesitamos alguien que aniquile al Rey Unity.'],
    ['Anciano', 'Pero no hubo hombre capaz de atravezar los muros del castillo del Rey que salga vivo.'],
    ['Guerrero', 'Yo lo haré. Lo juro por mis dioses y mi amada Dulcinea Konypyon.'],
    ['Anciano', 'No será tarea fácil. Además del dragón, hay muchos guardias en el castillo.'],
    ['Guerrero', 'Me infiltraré en el castillo, daré muerte al Rey Unity y comeremos dragón con papas esta noche.'],
    ['Guerrero', '¡Lo juro! ¡Como que me llamo Alva Majo!'],
    ['Guerrero', 'Desarrollador de Videojuegos indie.'],
    ['Guerrero', 'Dime donde está el castillo. Te lo ordeno.'],
    ['Anciano', 'El castillo está detrás de las siete colinas en dirección al sur.'],
    ['Anciano', 'Avisaré a los mercaderes del pueblo que tu irás. Tal vez puedan ayudarte a ingresar al castillo.'],
]

export default dialog